services:
  backend:
    container_name: code_practice_backend
    build: # remove
      context: ./backend 
    image: name/nginx:latest # example
    ports:
      - "10601:5000"
    volumes: # name to myapp
      - ./backend:/app
      - /app/node_modules
    env_file: # remove this
      - ./backend/.env
    environment: # use this
      - DEBUG=true
    command: npm run dev
    networks: # remove
      - code-practice-app

  frontend:
    container_name: code_practice_frontend
    build:
      context: ./frontend/SE65-SENIOR-PROJECT
    image: frontend
    ports:
      - "10602:5173"
    volumes:
      - ./frontend/SE65-SENIOR-PROJECT:/app
      - /app/node_modules
    env_file:
      - ./frontend/SE65-SENIOR-PROJECT/.env
    command: npm run dev
    networks:
      - code-practice-app
    
  coderunner:
    container_name: code_practice_coderunner
    build:
      context: ./coderunner
    image: coderunner
    ports:
      - "10603:3000"
    volumes:
      - ./coderunner:/app
      - /app/node_modules
    env_file:
      - ./coderunner/.env
    command: npm run dev
    networks:
      - code-practice-app

networks:
  code-practice-app:
    external: true