services:
  backend:
    container_name: code_practice_backend
    build:
      context: ./backend
    image: backend
    ports:
      - "10601:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    command: npm run dev
    networks:
      - code-practice-app

  frontend:
    container_name: code_practice_frontend
    build:
      context: ./frontend/SE65-SENIOR-PROJECT
    image: frontend
    ports:
      - "10602:5173"
    volumes:
      - ./frontend/SE65-SENIOR-PROJECT:/app
      - /app/node_modules
    env_file:
      - ./frontend/SE65-SENIOR-PROJECT/.env
    command: npm run dev
    networks:
      - code-practice-app
    
  ts-code-runner:
    container_name: code_practice_ts_code_runner
    build:
      context: ./ts-code-runner
    image: ts-code-runner
    ports:
      - "10603:3000"
    volumes:
      - ./ts-code-runner:/app
      - /app/node_modules
    env_file:
      - ./ts-code-runner/.env
    command: npm run dev
    networks:
      - code-practice-app

networks:
  code-practice-app:
    external: true