services:
  backend:
    build:
      context: ./backend
    image: backend
    ports:
      - "10601:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    command: npm run dev

  frontend:
    build:
      context: ./frontend/SE65-SENIOR-PROJECT
    image: frontend
    ports:
      - "10602:5173"
    volumes:
      - ./frontend/SE65-SENIOR-PROJECT:/app
      - /app/node_modules
    command: npm run dev
    
  ts-code-runner:
    build:
      context: ./ts-code-runner
    image: ts-code-runner
    ports:
      - "10603:3000"
    volumes:
      - ./ts-code-runner:/app
      - /app/node_modules
    command: npm run dev
